[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "openai>=2.0.0",
    "pydantic>=2.11.9",
    "requests>=2.32.5",
    "streamlit>=1.50.0",
]
