[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
base = "dark"
primaryColor = "#008080"
backgroundColor = "#0B0F14"
secondaryBackgroundColor = "#111827"
textColor = "#E5E7EB"
font = "sans serif"
